### ISSUE TITLE
「讨论帖」佛经规格

### ISSUE THREAD

**Issue by shijinkui** [sutras/sutra-fmt#1]
### 开新issue讨论规格事情

---

@RayCHOU @mahawu @heavenchou

RayCHOU:
我寫的程式版權已改為 Apache-2.0。

CBETA 的 XML schema 是基於 TEI: http://www.tei-c.org/
佛典中的特例，TEI 未規範到的，CBETA 才設計自己的標記方式。
標記設計未臻理想的地方，是有不少。
因為 CBETA 一開始做的時候，並不了解全部佛典的情況，XML schema 是邊做邊修改的。
您覺得不合理的設計，或許可以提出更好的方案與 CBETA 討論，
不過標記方式的變動，影響很大，CBETA 不一定能很快調整就是了。

－－－－－－－－－－－－
我的想法是，不动xml, 基于xml生成标准的json格式。
确定一套标准的佛经规格。

meta信息, 如: 来源，版权，reversion，最后修订时间，对应实体书的信息
经文header信息，包括文件名，xml-p5对应的文件路径，经题，翻译者，在藏经中的位置，目录，卷数
佛经正文，序言（一个或者多个），品次，卷次，经题 正文，目前看到两类，一个是P标记，一个是lg标记，lg应该是偈诵了，区别对待

**Comment by RayCHOU** [comment]
JSON 是 JavaScript Object Notation，
基本上它是設計用來表達 Object，結構性的資料，
這用來記錄佛典的 metadata 不錯，
但若要連佛典文字這種連續性的文本資料都要以 JSON 來表達，恐怕是會有困難。
您可以試看看，但我想不會那麼容易，
除非許多在 XML 裡的資訊在轉為 JSON 時願意放棄掉。
這樣的話，這個 JSON 格式的佛典規格能否成為標準，恐怕會是個大問題。
如果它不能完整的記錄佛典的相關資訊的話。

關於 CBETA XML 標記的說明，我們有一些不完整的文件可以供您參考：
http://wiki.ddbc.edu.tw/pages/CBETA_XML_P5_使用手冊
http://wiki.ddbc.edu.tw/pages/CBETA_XML_P5a_Elements

**Comment by shijinkui** [comment]
是的，佛经的规格不是那么复杂, json可以表达佛经内容。meta信息比较复杂，比如修订记录, 修改内容对照表，这些meta信息可以由git的issue和pull request满足。
佛经的正文标签p和lg

两个格式化后的样本，结构简单的《佛說妙色王因緣經》，序言和品次结构复杂的《梁朝傅大士頌金剛經》，@RaCHOU 有时间帮过目看下有无错谬。转的markdown还是比较适合阅读的:)  
https://github.com/sutras/sutra-fmt/tree/master/src/main/resources

**Comment by mahawu** [comment]
2015-11-02 0:07 GMT+08:00 时金魁 notifications@github.com:

> 佛经的规格不是那么复杂

​這句話有待斟酌。佛教藏經的主體一般分成經、律、論三類​，這三類之外還有經疏、律疏、論疏、諸宗、史傳、事彙、目錄等等，各類的規格架構出入頗大的。

​maha​

## 

吳寶原 Maha Wu
中華電子佛典協會(CBETA) http://www.cbeta.org/
CBETA Facebook https://www.facebook.com/cbeta.org / Maha Facebook
https://www.facebook.com/maha1963

**Comment by RayCHOU** [comment]
> 佛经的规格不是那么复杂

如果您願意放棄目前 CBETA XML 之中許多豐富的資訊，
正文之中只保留文字、段落 p、偈頌 lg,
那要說不是那麼複雜，才有可能成立。

> 佛经的正文标签p和lg

您目前產生的 JSON 結構，如果 p 與 lg 交錯出現，似乎不能很好的表達？

何況除了 p 與 lg 之外還有這些：
- 大正藏出處冊數、頁碼、行號
- 目次結構
- table 表格
- list 清單
- figure, graphic 插圖
- 校勘、各版本用字、CBETA 修訂用字
- 缺字問題：中文、悉曇文、蘭札體

梁朝傅大士頌金剛經.json 看起來比 XML 更令人頭大、更難閱讀。
如果願意放棄大部份資訊，那我覺得產生另一個簡化版的 XML 似乎更可行。
但是哪些資訊可以放棄？哪些數位佛典必須有的資訊？這就值得討論。
像目前 Christian Wittern 做的 [Mandoku](http://www.mandoku.org/)，就簡化了非常多。
看來，一個簡化版的 CBETA 佛典格式，似乎是普遍的需求。

**Comment by RayCHOU** [comment]
忽然想到，在這裡討論，參與的人很少，
但有一些朋友是對這些議題有興趣的，
时先生或許可以考慮到以下 Facebook 社團討論：
- https://www.facebook.com/groups/volunteers.cbeta/
- https://www.facebook.com/groups/buddhistinformatics/

啊，但是 Facebook 可能被封鎖？

**Comment by shijinkui** [comment]
访问不了的，墙...

**Comment by shijinkui** [comment]
@RayCHOU  正文以外的所有元数据，单独放到一个对象里。其实读者焦点在佛经，其次是meta信息。
另外一个现象是：各大网站佛经跟cbeta不同步，网络上的发现cbeta的校对问题，也无法反馈，这才是更麻烦的事情。这也是我想搞这个事情的初衷。

p和lg交叉是昨晚遇到的，我用Array[_]，数组里存object，在用内容是，match一下对象类型即可。scala里match很方便。

> 您目前產生的 JSON 結構，如果 p 與 lg 交錯出現，似乎不能很好的表達？
> 何況除了 p 與 lg 之外還有這些：
> 大正藏出處冊數、頁碼、行號
> 目次結構
> table 表格
> list 清單
> figure, graphic 插圖
> 校勘、各版本用字、CBETA 修訂用字
> 缺字問題：中文、悉曇文、蘭札體

@mahawu 
简单想对于meta数据而言。毫无轻视之意。上周读了这篇文章，对cbeta的工作肃然起敬。之前担心日本那边的版权问题，现在来看毫无问题。非常感谢cbeta这些年的持续努力。[《杏壇衲履：恆清法師訪談錄》](http://www.cbeta.org/data/cbeta10y/cbhistory.htm) 
經、律、論三類​的内容格式，有啥不同么，或者有文档说明么。

**Comment by shijinkui** [comment]
@RayCHOU @mahawu 
前些天调研cbeta整理的文档，现在看来语气略有偏激（不了解全部）。
https://github.com/sutras/checklist

大致思路两点：
1. 佛经校对。github提PR，公开透明可追溯和恢复，任何人都可参与提PR
2. 版权无限制。apache V2、BSD、MIT，即鼓励商业软件推广佛经，佛经类的手机app需要增多
3. 提供方便的元数据格式，json

**Comment by mahawu** [comment]
「网络上的发现cbeta的校对问题，也无法反馈，这才是更麻烦的事情。」——其實只要簡單的 email 到 service@cbeta.org
就可以把問題反映給我們。至於透過 github 來回饋問題及討論，基本上會玩 github 大都要有一定程度的軟體操作經驗，github
 對一般人來說門檻太高（特別是研究佛學的文科學者）。

「經、律、論三類​的内容格式，有啥不同么，或者有文档说明么。」——這不是三言兩語可以表達的，或許你從 Ray 提供的 CBETA
標記規範可以看出端倪，也可以從 CBReader 的「大正藏-部」書目抽樣看看實際文本的各種類型。

先說清楚，我的角色是數位化文本的編輯者，我不是程式人員，所以在標記及程式應用的認識上還要多向你們學習。

2015-11-02 10:17 GMT+08:00 时金魁 notifications@github.com:

> @RayCHOU https://github.com/RayCHOU @mahawu https://github.com/mahawu
> 前些天调研cbeta整理的文档，现在看来语气略有偏激（不了解全部）。
> https://github.com/sutras/checklist
> 
> 大致思路两点：
> 1. 佛经校对。github提PR，公开透明可追溯和恢复，任何人都可参与提PR
> 2. 版权无限制。apache V2、BSD、MIT，即鼓励商业软件推广佛经，佛经类的手机app需要增多
> 3. 提供方便的元数据格式，json
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sutras/sutra-fmt/issues/1#issuecomment-152891442.

## 

吳寶原 Maha Wu
中華電子佛典協會(CBETA) http://www.cbeta.org/
CBETA Facebook https://www.facebook.com/cbeta.org / Maha Facebook
https://www.facebook.com/maha1963

**Comment by RayCHOU** [comment]
> 访问不了的，墙...

墻不是可以翻嗎？ ^_^

真的，來 Facebook 社團，比較多人討論，比較有熱情，也有多角度的思考面向可以參考。

**Comment by shijinkui** [comment]
@RayCHOU 最近比较严，各种翻墙工具都歇菜了... 可怜的天朝上国。。。 我有qq群和微信群，这俩在大陆用的比较多些。主要懒得翻了，我也就是晚上最多一个小时写代码的时间，白天要上班干活，哈哈～

@mahawu 根本问题还是校对过程的可追溯，可回滚，透明检察。cbeta到了这个成功阶段，可以考虑下下一步的方式。毕竟世界都变了，不变变就老了，哈。一个人一个团体的智慧，不如全世界人的智慧。另外一个问题就是：佛经的维护不应该局限在一个团体和个人上，向前延伸五百年一千年看看。佛经必须要有一个永久的延续承载体系，个人和团体都是昙花一现。所以，我个人觉得两件事要做：1. 佛经网络化规范化，普及阅读；2. 宣纸线装本的延续（这个在杭州留下镇，两位法师在做）。若无大众的参与，本无法流必要。所以佛经还是要回归到大众上来的，阅读，流传，延续，校对一切工作。个人浅见:)

**Comment by mahawu** [comment]
確實，github 的「可追溯，可回滚，透明检察」很棒。贊同「维护不应该局限在一个团体和个人上」，大家一起努力吧！

2015-11-02 12:04 GMT+08:00 时金魁 notifications@github.com:

> @RayCHOU https://github.com/RayCHOU 最近比较严，各种翻墙工具都歇菜了... 可怜的天朝上国。。。
> 我有qq群和微信群，这俩在大陆用的比较多些。主要懒得翻了，我也就是晚上最多一个小时写代码的时间，白天要上班干活，哈哈～
> 
> @mahawu https://github.com/mahawu
> 根本问题还是校对过程的可追溯，可回滚，透明检察。cbeta到了这个成功阶段，可以考虑下下一步的方式。毕竟世界都变了，不变变就老了，哈。一个人一个团体的智慧，不如全世界人的智慧。另外一个问题就是：佛经的维护不应该局限在一个团体和个人上，向前延伸五百年一千年看看。佛经必须要有一个永久的延续承载体系，个人和团体都是昙花一现。所以，我个人觉得两件事要做：1.
> 佛经网络化规范化，普及阅读；2.
> 宣纸线装本的延续（这个在杭州留下镇，两位法师在做）。若无大众的参与，本无法流必要。所以佛经还是要回归到大众上来的，阅读，流传，延续，校对一切工作。个人浅见:)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sutras/sutra-fmt/issues/1#issuecomment-152907730.

## 

吳寶原 Maha Wu
中華電子佛典協會(CBETA) http://www.cbeta.org/
CBETA Facebook https://www.facebook.com/cbeta.org / Maha Facebook
https://www.facebook.com/maha1963

**Comment by shijinkui** [comment]
@mahawu @RayCHOU 二位大德，cbeta的校对工作能完全放到github上么。我们这边有很多人想参与这个事情。不分国别的做同一件事情。这两天我会画一个流程图出来大家来讨论看。版本发布，提PR，merge PR等规范化，长远来看，这种方式比较靠谱

**Comment by mahawu** [comment]
我們有兩個版本，一個是公開的穩定版本(xml-p5)，另一個是不公開的進行中版本(xml-p5a)。
如果要接受 pull request，「穩定版本(xml-p5)」似乎不適合，因為它不是最新的，最新的是「進行中版本(xml-p5a)」。
但「進行中版本(xml-p5a)」適合公開嗎？這要請教 Ray 跟 Heaven 的意見。

2015-12-25 14:31 GMT+08:00 时金魁 notifications@github.com:

> @mahawu https://github.com/mahawu @RayCHOU https://github.com/RayCHOU
> 二位大德，cbeta的校对工作能完全放到github上么。我们这边有很多人想参与这个事情。不分国别的做同一件事情。这两天我会画一个流程图出来大家来讨论看。版本发布，提PR，merge
> PR等规范化，长远来看，这种方式比较靠谱
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sutras/sutra-fmt/issues/1#issuecomment-167200220.

## 

吳寶原 Maha Wu
中華電子佛典協會(CBETA) http://www.cbeta.org/
CBETA Facebook https://www.facebook.com/cbeta.org / Maha Facebook
https://www.facebook.com/maha1963

**Comment by shijinkui** [comment]
@mahawu  使用git提交变更，每个次变更都有记录，也就不需要加reversion了。在github上可以把pr合并到master上。半年度或者一年，打一个tag，如：v1.10, 这样一个好处是，所有的校对是透明的，所有人不分国别的都能参与到校对中来。未来所有的网站，手机app都以某一个tag为准，定时更新最新版本。

痛苦的是需要大家对git的熟练。

另外一件事情，个人觉得cbeta可以把xml规范化，所有的经文统一一个标准格式。这个更有价值，校对是长期的，标准化是急迫的。

git flow参考:
1. https://github.com/nvie/gitflow
2. http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/
3. http://danielkummer.github.io/git-flow-cheatsheet/index.zh_CN.html

**Comment by shijinkui** [comment]
@mahawu @RayCHOU 二位大德, 
经文的标准化格式元素: 经题，副标题，内容，翻译者，提供者，来源刻本，最新修改时间，品次目录（品名，品次内容），卷次目录（卷名，卷内容），特殊词汇对照表，所在藏经名／部次 （请补充）

初步计划时，我这边会fork一下cbeta-org/xml-p5, 在此基础上修改，定期合并xml-p5。在一个tag上做分发。

分发：把上述标准内容生成不同的格式，有些信息必须展示，如：藏经／部／经题，这种目录。还有最后修改时间等，提供者和刻板。类似萧镇国大德出力贡献，读者不可不知。

校对和分发流通，尽量标准化，无局限性的做，长远来看，这样会好些。:)

**Comment by mahawu** [comment]
請把 https://github.com/heavenchou 也加入討論。

**Comment by RayCHOU** [comment]
加入 @heavenchou

@mahawu CBETA 的 xml p5a 已經公開很久了啊 ^_^

@shijinkui 建議你 fork CBETA 的 xml p5a: https://github.com/cbeta-git/xml-p5a
因為 CBETA 的 p5 是由 p5a 產生的。
修改之後提 pull request 給 CBETA 審核是否接受 merge.

願意使用 git 的人，可以用這樣的流程來做，
一般的使用者可能還是直接寫 email 給 CBETA 方便一點，
CBETA 可以把貢獻者寫在上傳 git 時的說明裡。

**Comment by mahawu** [comment]
我對外都是說 p5 啦。但其實 p5a 也同時公開在 github 上，找就有了。
就照 Ray 建議的試試看，我只擔心如果 pull request 太多，我們恐怕沒時間應付。

**Comment by shijinkui** [comment]
@RayCHOU @mahawu @heavenchou   三位大德，前些天转xml-p5的时候，发现各个经文格式并不是完全统一的，cbeta-p5a.rnc比较复杂，不深入了解的，不容易下手，哈。抽象出来一个cbeta-p5a.rnc的min格式版本，更便于程序开发。

cbeta未来是不是commiter的功能多一些较好，哈。

今天中午河北柏林寺那边的佛学院的杨新宇博士来阿里西溪园区，聊了些这方面的事情。
杨博士在大陆大力推广阅读藏经活动，我从09年开始读藏经，颇有收获，业余做了《一苇阅读网》http://www.txt7.com.cn/  

佛经的校对和流布，可以再做深一步，把整个流程梳理规范。甚至成立基金会来支持这个事情。

**Comment by RayCHOU** [comment]
@mahawu 
p5a 的 pull request 我猜不會太多，因為那真的複雜到不是一般人能修訂的 ^_^

@shijinkui @heavenchou
或許可以考慮一個簡化的格式, 
例如 CBETA 的 normal 版純文字格式，
它在檔首也有一些基本的 metadata 資訊，
CBETA 放一份 normal 版在 GitHub 上，
@shijinkui 這邊就 fork 這份 normal 版來修訂，這樣可能容易一點，
@mahawu 收到 pull request 就可能會多一點，
這樣不知道是該高興 還是該傷腦筋 ^_^

以錯字訂正來說，這樣應該是足夠的，
如果覺得 normal 版的資訊還不夠，
就要看還少些什麼，是否朝 mandoku 或 markdown 格式考慮。

@shijinkui 知道 CBETA 的 normal 版長什麼樣子嗎？

**Comment by shijinkui** [comment]
@RayCHOU normal版本有标准格式么，还不知道...  看到大陆这边用的txt版本，信息缺失的厉害，大部分只有: 经题，内容，翻译者。

@RayCHOU @mahawu @heavenchou  下面是前些天写了几行代码转的样例，看有问题么:
- [佛說妙色王因緣經](https://github.com/sutras/sutra-fmt/blob/master/src/main/resources/%E4%BD%9B%E8%AA%AA%E5%A6%99%E8%89%B2%E7%8E%8B%E5%9B%A0%E7%B7%A3%E7%B6%93.markdown)
- [梁朝傅大士頌金剛經](https://github.com/sutras/sutra-fmt/blob/master/src/main/resources/%E6%A2%81%E6%9C%9D%E5%82%85%E5%A4%A7%E5%A3%AB%E9%A0%8C%E9%87%91%E5%89%9B%E7%B6%93.markdown)

**Comment by heavenchou** [comment]
看了以上討論, 我想這大概可以分成二件事.

一個是修訂的資料, 過去是寫信來告知, 由 @mahawu 處理, 最後修訂至 P5a (人工處理的版本), 再自動轉成 P5 (對外公開的 XML)

如果這個步驟是修訂 P5a 再向 CBETA 提出要求, 也差不多是由 @mahawu 那邊過濾修訂. :)

@RayCHOU 提的 normal 來處理錯字修正, 也是不錯的方法.

另一件事就是若要由 P5a 產生一些新的版本及應用, 那也是我們樂見的發展. ^_^

**Comment by heavenchou** [comment]
> 经文的标准化格式元素: 经题，副标题，内容，翻译者，提供者，来源刻本，最新修改时间，品次目录（品名，品次内容），卷次目录（卷名，卷内容），特殊词汇对照表，所在藏经名／部次 （请补充）

目前的 XML 中, 好像缺了 "所在藏经名／部次" , 這倒是值得放入的.

**Comment by RayCHOU** [comment]
@shijinkui 問：normal版本有标准格式么？
這請問 @heavenchou 可以在哪裡找到 CBETA normal 版？
以前是可以從網站上下載，但是剛找了一下沒找到。

@shijinkui 做的 markdown 格式，
這做為應用的格式之一，是很好的，
但是若要做為錯字訂正的交流格式就不太適合，
因為它不是依原書換行，裡面沒有行號，
這樣對 @mahawu 來說，要修訂是比較困難的。

**Comment by mahawu** [comment]
「因為它不是依原書換行，裡面沒有行號，這樣對 @mahawu 來說，要修訂是比較困難的。」——這倒還好，前後文全文檢索一下，不難找到。

不過，你們說的 normal 版本，如果是純粹提供一個修訂管道，那麼它如何跟 p5a 同步？

**Comment by heavenchou** [comment]
目前沒有提供 Normal , 那時好像是網路版更新時間有限, 就沒有做 Normal 上網了.

http://tripitaka.cbeta.org/T01

現在只有  ePub, azw3, PDF , 這大概是適合比較多人在使用的版本.

至於 maha 上面提到的如何同步, 大概就是和 email 修訂一般, 別人提出差異, maha 檢查後確定要改, 就依一般流程,  CBETA 修改 P5a 、P5, 然後更新 git 吧.

**Comment by shijinkui** [comment]
画了张图，大家看看，不知道表达清楚了么  @RayCHOU @mahawu @heavenchou 

@RayCHOU  
1. 文本格式不能用于程序，没有结构化。 
2. 不维护经过转化的内容，只在源头维护(xml-p5)。程序转化格式，一般不超过三分钟。

![](https://raw.githubusercontent.com/sutras/checklist/master/sutras_proof.jpg)

**Comment by RayCHOU** [comment]
@shijinkui 你可以試看看，如果真的有很多人願意直接修訂 p5a 提交給 CBETA，那當然是最好。
但是你自己也說了「cbeta-p5a.rnc比较复杂，不深入了解的，不容易下手」。

**Comment by mahawu** [comment]
你們知道 gitbook 嗎？看看這個：
https://www.gitbook.com/book/budda/tripitaka/details

這 gitbook 是 gitbhub 的姐妹產品，有點意思，這裡有相關介紹：
http://www.jianshu.com/p/63dc1bc6b1d9

我不知道這樣的型式是否適合讀者「提出修訂」，然後會有「版本修訂記錄」。麻煩你們研究一下了。

maha

RayCHOU notifications@github.com 於 2015年12月25日 下午8:39 寫道：

**Comment by mahawu** [comment]
2015-12-25 17:48 GMT+08:00 时金魁 notifications@github.com:

> 不维护经过转化的内容，只在源头维护(xml-p5)。程序转化格式，一般不超过三分钟。
> 
> ​這就是我​在意的。如果是透過 normal 版本界面給人家提出修訂意見，那麼我去改 p5a，改完之後，是否只要「按個鈕」就可以同步更新 p5 及
> normal？

**Comment by shijinkui** [comment]
@RayCHOU 这个需要`cbeta-p5a.rnc`的说明文档完善一点，每一个元素有中文介绍及示例，会比较好上手:)

>   這就是我​在意的。如果是透過 normal 版本界面給人家提出修訂意見，那麼我去改 p5a，改完之後，是否只要「按個鈕」就可以同步更新 p5 及 normal？

@mahawu 是的，这就是我写这个sutra-fmt程序的初衷:)   只需要维护一个源，其它任何格式都可以通过工具自动转。只需要定期自动转一个发行版本就好。
 xml-p5 -> json -> markdown -> html/gitbook， 这些生成的json/md/html格式都在github上作为只读发行出去。  
json是应用程序可识别的，用起来比较方便。其它格式都从json格式自动生成。

**Comment by mahawu** [comment]
程式方面再請 Ray, Heaven 給意見了。

2015-12-25 22:06 GMT+08:00 时金魁 notifications@github.com:

> @RayCHOU https://github.com/RayCHOU 这个需要cbeta-p5a.rnc
> 的说明文档完善一点，每一个元素有中文介绍及示例，会比较好上手:)
> 
> 這就是我​在意的。如果是透過 normal 版本界面給人家提出修訂意見，那麼我去改 p5a，改完之後，是否只要「按個鈕」就可以同步更新 p5 及
> normal？
> 
> @mahawu https://github.com/mahawu 是的，这就是我写这个sutra-fmt程序的初衷:)
> 只需要维护一个源，其它任何格式都可以通过工具自动转。只需要定期自动转一个发行版本就好。
> xml-p5 -> json -> markdown -> html/gitbook，
> 这些生成的json/md/html格式都在github上作为只读发行出去。
> 
> json是应用程序可识别的，用起来比较方便。其它格式都从json格式自动生成。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sutras/sutra-fmt/issues/1#issuecomment-167237073.

## 

吳寶原 Maha Wu
中華電子佛典協會(CBETA) http://www.cbeta.org/
CBETA Facebook https://www.facebook.com/cbeta.org / Maha Facebook
https://www.facebook.com/maha1963

**Comment by RayCHOU** [comment]
程式哪方面？

> 改 p5a，改完之後，是否只要「按個鈕」就可以同步更新 p5 及 normal？

是，但要先做一些動作把這個按鈕叫出來⋯⋯

既然不方便用 facebook,
我們是不是乾脆用 email 討論就好了？
這樣副本要加人也容易一點。

或是有其他方便大陸和台灣協作的社群平台？
總覺得這事只有我們三個討論太封閉、太可惜。

## 

Ray Chou 周邦信, 法鼓文理學院 圖書資訊館 數位典藏組 專員
Office: 02-2498-0707#2233, 手機: 0937-425-020

2015-12-29 10:58 GMT+08:00 吳寶原 notifications@github.com:

**Comment by shijinkui** [comment]
@RayCHOU @mahawu @heavenchou  微信用么

**Comment by RayCHOU** [comment]
這樣好了，
麻煩金𣁽兄給幾個選擇，我在 facebook CBETA 社群讓大家投票喜好的平台，
這樣如何？

## 

Ray Chou 周邦信, 法鼓文理學院 圖書資訊館 數位典藏組 專員
Office: 02-2498-0707#2233, 手機: 0937-425-020

2015-12-30 14:45 GMT+08:00 shijinkui notifications@github.com:

**Comment by shijinkui** [comment]
@RayCHOU 

可选的:
1. 微信(wechat)    这个最及时, 手机app，用的最多。微信群。
2. QQ群    目前QQ不活跃了
3. 邮件组   这个有归档，比较可以沉淀内容，缺点是不及时。

_推荐用`微信`, 重要问题讨论结果帖到github的issue中记录。_

墙是个麻烦事情, 很多人不会翻，并且翻墙产品时常被封。GWF越来越聪明。只要不涉及台*-独等敏感问题，微信基本满足的:)

**Comment by RayCHOU** [comment]
我已經在 Facebook 社團 「CBETA 志工社群」發佈問卷調查了。

## 

Ray Chou 周邦信, 法鼓文理學院 圖書資訊館 數位典藏組 專員
Office: 02-2498-0707#2233, 手機: 0937-425-020

2015-12-30 14:56 GMT+08:00 shijinkui notifications@github.com:

**Comment by yapcheahshen** [comment]
我也來了。

**Comment by RayCHOU** [comment]
歡迎前輩 Yap 𦲷臨指導。

## 

Ray Chou 周邦信, 法鼓文理學院 圖書資訊館 數位典藏組 專員
Office: 02-2498-0707#2233, 手機: 0937-425-020

2015-12-30 18:39 GMT+08:00 yap cheah shen notifications@github.com:

**Comment by RayCHOU** [comment]
@shijinkui 

投票結果：郵件組 4 票，其他都 0票。

Linus Hsao 的意見：我覺得emai的mailling list進入門檻最低，使用人數也比較多，相較之下微信和QQ只有大陸人才會使用，其他地方使用率太低。很多世界性的open source方案都是已mailling list在討論的，歷久不衰。

**Comment by shijinkui** [comment]
@RayCHOU  好的, 那就mail list

**Comment by shijinkui** [comment]
https://groups.google.com/forum/#!forum/sutra mail list

在 2015-12-30 18:48:54，"RayCHOU" notifications@github.com 写道：
歡迎前輩 Yap 𦲷臨指導。

## 

Ray Chou 周邦信, 法鼓文理學院 圖書資訊館 數位典藏組 專員
Office: 02-2498-0707#2233, 手機: 0937-425-020

2015-12-30 18:39 GMT+08:00 yap cheah shen notifications@github.com:

**Comment by RayCHOU** [comment]
已將網址公告在 facebook 「CBETA 志工社群」。

## 

Ray Chou 周邦信, 法鼓文理學院 圖書資訊館 數位典藏組 專員
Office: 02-2498-0707#2233, 手機: 0937-425-020

2016-01-06 14:55 GMT+08:00 shijinkui notifications@github.com:
